(evil-leader/set-key "oc" 'org-capture)
(evil-leader/set-key "ol" 'org-store-link)
(evil-leader/set-key "oa" 'org-agenda)
(evil-leader/set-key "oj" 'org-clock-jump-to-current-clock)
(evil-leader/set-key "om" 'org-match-sparse-tree)
